# Generated by Django 5.1.4 on 2025-01-27 21:11

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Halaqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='اسم الحلقة')),
                ('level', models.CharField(max_length=256, verbose_name='مستوى الحلقة')),
                ('type_class', models.CharField(max_length=256, verbose_name='نوع القراءة')),
                ('count', models.IntegerField(verbose_name='الطاقة الاستيعابية للحلقة')),
                ('start_time', models.TimeField(verbose_name='وقت بداية الحلقة')),
                ('end_time', models.TimeField(verbose_name='وقت نهاية الحلقة')),
                ('activate', models.BooleanField(default=True, verbose_name='تفعيل')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('activate', models.BooleanField(default=True, verbose_name='تفعيل')),
                ('first_name', models.CharField(max_length=256, verbose_name='الأسم الأول للطالب')),
                ('second_name', models.CharField(max_length=256, verbose_name='الأسم الثاني للطالب')),
                ('last_name', models.CharField(max_length=256, verbose_name='لقب الطالب')),
                ('birthday', models.DateField(verbose_name='تاريخ الميلاد')),
                ('nationality', models.CharField(max_length=256, verbose_name='الجنسية')),
                ('country', models.CharField(max_length=256, verbose_name='الدولة')),
                ('gender', models.CharField(max_length=256, verbose_name='الجنس')),
                ('email', models.EmailField(max_length=254, verbose_name='الإيميل')),
                ('language', models.CharField(max_length=256, verbose_name='اللغة التي تعرفها')),
                ('mobile', models.CharField(max_length=256, verbose_name='رقم الجوال')),
                ('whatsapp', models.CharField(max_length=15, null=True, verbose_name='رقم الواتس اب')),
                ('username', models.CharField(default='default_username', max_length=250, verbose_name='اسم المستخدم')),
                ('password', models.CharField(max_length=256, verbose_name='كلمة المرور')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('activate', models.BooleanField(default=True, verbose_name='تفعيل')),
                ('name', models.CharField(max_length=256, verbose_name='الاسم الثلاثي')),
                ('email', models.EmailField(max_length=254, verbose_name='الإيميل')),
                ('password', models.CharField(max_length=256, verbose_name='كلمة المرور')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maqraapp.halaqa', verbose_name='الحلقة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maqraapp.students', verbose_name='الطالب')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('count_bage', models.FloatField(verbose_name='عدد الصفحات')),
                ('task_student', models.CharField(choices=[('1', 'حفظ'), ('2', 'مراجعة'), ('3', 'تلقين')], default='1', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maqraapp.students', verbose_name='الطالب')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='الاسم الأول')),
                ('second_name', models.CharField(max_length=256, verbose_name='الاسم الثاني')),
                ('last_name', models.CharField(max_length=256, verbose_name='اللقب')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='الإيميل')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SA', verbose_name='رقم الجوال')),
                ('mobile_whatsapp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='SA', verbose_name='رقم الواتس')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='الجنس')),
                ('birthday', models.DateField(verbose_name='تاريخ الميلاد')),
                ('nationality', models.CharField(max_length=256, verbose_name='الجنسية')),
                ('country', models.CharField(max_length=256, verbose_name='الدولة')),
                ('certificates', models.CharField(blank=True, max_length=256, null=True, verbose_name='شهادات وإجازات الحفظ')),
                ('language', models.CharField(choices=[('Arabic', 'Arabic'), ('English', 'English'), ('French', 'French')], max_length=256, verbose_name='اللغة التي تعرفها')),
                ('password', models.CharField(max_length=256, verbose_name='كلمة المرور')),
                ('career_path', models.CharField(choices=[('1', 'تأسيس'), ('2', 'إجازة1'), ('3', 'إجازة2'), ('4', 'حفظ')], max_length=256, verbose_name='المسار الذي ترغب في التدريس')),
                ('cv_teacher', models.FileField(blank=True, null=True, upload_to='teachers/cvs/', verbose_name='السيرة الذاتية')),
                ('username', models.CharField(max_length=256, unique=True, verbose_name='اسم المستخدم')),
                ('activate', models.BooleanField(default=True, verbose_name='تفعيل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='halaqa',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maqraapp.teachers', verbose_name='الأستاذ'),
        ),
        migrations.CreateModel(
            name='Teatcher_class_supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maqraapp.supervisor', verbose_name='المشرف')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maqraapp.teachers', verbose_name='المدرس')),
                ('teacher_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maqraapp.halaqa', verbose_name='الحلقة')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('supervisor', 'Supervisor'), ('admin', 'Admin')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
