# Generated by Django 5.1.4 on 2025-01-27 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='اسم القسم')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='halaqa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maqraapp.halaqa', verbose_name='الحلقة'),
        ),
        migrations.AlterField(
            model_name='halaqa',
            name='type_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maqraapp.typeread', verbose_name='نوع القراءة'),
        ),
        migrations.AlterField(
            model_name='typeread',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نوع القراءة'),
        ),
        migrations.AddField(
            model_name='halaqa',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maqraapp.department', verbose_name='القسم'),
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
    ]
