# Generated by Django 5.1.4 on 2025-01-29 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0002_department_students_halaqa_alter_halaqa_type_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='ayah',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاية'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='ayah_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الاية'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'فئة المبتدئين'), ('2', 'فئة ثلاثة أجزاء'), ('3', 'فئة خمسة أجزاء'), ('4', 'فئة عشرة أجزاء'), ('5', 'فئة خمسة عشر جزء'), ('6', 'فئة عشرون جزء'), ('7', 'فئة خمسة وعشرون جزء')], max_length=10, null=True, verbose_name='الفئة'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='department',
            field=models.CharField(default=1, max_length=255, verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='halaqa_name',
            field=models.CharField(default=1, max_length=255, verbose_name='اسم الحلقة'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='msar',
            field=models.CharField(default=1, max_length=255, verbose_name='المسار'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='surah',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='السورة'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='weekly_plan',
            field=models.TextField(blank=True, null=True, verbose_name='خطة الأسبوع'),
        ),
        migrations.AlterField(
            model_name='studenttask',
            name='task_student',
            field=models.CharField(choices=[('1', 'حفظ'), ('2', 'مراجعة'), ('3', 'تلقين')], default='1', max_length=10, verbose_name='مهمة الطالب'),
        ),
        migrations.CreateModel(
            name='Msar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='المسار')),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maqraapp.department', verbose_name='القسم')),
            ],
        ),
        migrations.AddField(
            model_name='halaqa',
            name='msar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maqraapp.msar', verbose_name='المسار'),
        ),
    ]
