# Generated by Django 5.1.4 on 2025-01-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0003_studenttask_ayah_studenttask_ayah_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttask',
            name='weekly_plan',
        ),
        migrations.AddField(
            model_name='studenttask',
            name='week_end',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية الأسبوع'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='week_number',
            field=models.IntegerField(default=1, verbose_name='رقم الأسبوع'),
        ),
        migrations.AddField(
            model_name='studenttask',
            name='week_start',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الأسبوع'),
        ),
    ]
