# Generated by Django 5.1.4 on 2025-01-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0004_remove_studenttask_weekly_plan_studenttask_week_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='ayah_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد الآيات'),
        ),
        migrations.AlterField(
            model_name='studenttask',
            name='week_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الأسبوع'),
        ),
    ]
