# Generated by Django 5.1.4 on 2025-01-31 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0005_studenttask_ayah_count_alter_studenttask_week_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMemorizationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=50)),
                ('msar', models.CharField(blank=True, max_length=50)),
                ('halaqa', models.CharField(blank=True, max_length=50)),
                ('task', models.CharField(choices=[('beginners', 'فئة المبتدئين'), ('three_parts', 'فئة ثلاثة أجزاء'), ('five_parts', 'فئة خمسة أجزاء'), ('ten_parts', 'فئة عشرة أجزاء'), ('fifteen_parts', 'فئة خمسة عشر جزء'), ('twenty_parts', 'فئة عشرون جزء'), ('twenty_five_parts', 'فئة خمسة وعشرون جزء')], default='beginners', max_length=20)),
                ('previous_surah', models.CharField(max_length=100)),
                ('previous_ayat', models.PositiveIntegerField(default=1)),
                ('current_surah', models.CharField(max_length=100)),
                ('current_ayat', models.PositiveIntegerField(default=1)),
                ('pages', models.PositiveIntegerField()),
                ('partial_page', models.FloatField(choices=[(0, '0'), (0.25, '0.25'), (0.5, '0.5'), (0.75, '0.75')])),
                ('grade', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maqraapp.students')),
            ],
        ),
    ]
