# Generated by Django 5.1.4 on 2025-01-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0006_dailymemorizationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymemorizationtask',
            name='juz',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
