# Generated by Django 5.1.4 on 2025-01-31 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0007_dailymemorizationtask_juz'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymemorizationtask',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
