# Generated by Django 5.1.4 on 2025-02-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0008_dailymemorizationtask_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailymemorizationtask',
            old_name='task',
            new_name='MemorizationTask',
        ),
        migrations.RemoveField(
            model_name='dailymemorizationtask',
            name='department',
        ),
        migrations.RemoveField(
            model_name='dailymemorizationtask',
            name='halaqa',
        ),
        migrations.RemoveField(
            model_name='dailymemorizationtask',
            name='juz',
        ),
        migrations.RemoveField(
            model_name='dailymemorizationtask',
            name='msar',
        ),
        migrations.AddField(
            model_name='dailymemorizationtask',
            name='memorized_ayat_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
