# Generated by Django 5.1.4 on 2025-02-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0009_rename_task_dailymemorizationtask_memorizationtask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='MemorizationTask',
            field=models.IntegerField(choices=[(1, 'فئة المبتدئين'), (2, 'فئة ثلاثة أجزاء'), (3, 'فئة خمسة أجزاء'), (4, 'فئة عشرة أجزاء'), (5, 'فئة خمسة عشر جزء'), (6, 'فئة عشرون جزء'), (7, 'فئة خمسة وعشرون جزء')], default=1),
        ),
    ]
