# Generated by Django 5.1.4 on 2025-02-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0010_alter_dailymemorizationtask_memorizationtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='current_surah',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='previous_surah',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
    ]
