# Generated by Django 5.1.4 on 2025-02-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0011_alter_dailymemorizationtask_current_surah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='current_ayat',
            field=models.PositiveIntegerField(choices=[], default=1),
        ),
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='previous_ayat',
            field=models.PositiveIntegerField(choices=[], default=1),
        ),
    ]
