# Generated by Django 5.1.4 on 2025-02-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0014_alter_dailymemorizationtask_current_surah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='current_surah',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='previous_surah',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
