# Generated by Django 5.1.4 on 2025-02-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0015_alter_dailymemorizationtask_current_surah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='partial_page',
            field=models.DecimalField(choices=[(0, '0'), (0.25, '0.25'), (0.5, '0.5'), (0.75, '0.75')], decimal_places=2, max_digits=3),
        ),
    ]
