# Generated by Django 5.1.4 on 2025-02-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0016_alter_dailymemorizationtask_partial_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='current_ayat',
            field=models.PositiveIntegerField(choices=[], default=1),
        ),
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='current_surah',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='partial_page',
            field=models.FloatField(choices=[(0, '0'), (0.25, '0.25'), (0.5, '0.5'), (0.75, '0.75')]),
        ),
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='previous_ayat',
            field=models.PositiveIntegerField(choices=[], default=1),
        ),
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='previous_surah',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
    ]
