# Generated by Django 5.1.4 on 2025-02-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0019_alter_dailymemorizationtask_current_ayat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='current_ayat',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='current_surah',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='previous_ayat',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dailymemorizationtask',
            name='previous_surah',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
