# Generated by Django 5.1.4 on 2025-02-06 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0021_dailyreviewtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTalqeenTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TalqeenTask', models.IntegerField(choices=[(1, 'فئة المبتدئين'), (2, 'فئة ثلاثة أجزاء'), (3, 'فئة خمسة أجزاء'), (4, 'فئة عشرة أجزاء'), (5, 'فئة خمسة عشر جزء'), (6, 'فئة عشرون جزء'), (7, 'فئة خمسة وعشرون جزء')], default=1)),
                ('previous_surah', models.CharField(blank=True, max_length=100)),
                ('previous_ayat', models.PositiveIntegerField(default=1)),
                ('current_surah', models.CharField(blank=True, max_length=100)),
                ('current_ayat', models.PositiveIntegerField(default=1)),
                ('pages', models.PositiveIntegerField()),
                ('partial_page', models.FloatField(choices=[(0, '0'), (0.25, '0.25'), (0.5, '0.5'), (0.75, '0.75')])),
                ('grade', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('memorized_ayat_count', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maqraapp.students')),
            ],
        ),
    ]
