# Generated by Django 5.1.4 on 2025-02-07 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0022_dailytalqeentask'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorization_task', models.IntegerField(choices=[(1, 'فئة 1'), (2, 'فئة 2'), (3, 'فئة 3'), (4, 'فئة 4'), (5, 'فئة 5'), (6, 'فئة 6'), (7, 'فئة 7')])),
                ('memorization_previous_surah', models.CharField(max_length=100)),
                ('memorization_previous_ayat', models.IntegerField()),
                ('memorization_current_surah', models.CharField(max_length=100)),
                ('memorization_current_ayat', models.IntegerField()),
                ('review_task', models.IntegerField(choices=[(1, 'فئة 1'), (2, 'فئة 2'), (3, 'فئة 3'), (4, 'فئة 4'), (5, 'فئة 5'), (6, 'فئة 6'), (7, 'فئة 7')])),
                ('review_previous_surah', models.CharField(max_length=100)),
                ('review_previous_ayat', models.IntegerField()),
                ('review_current_surah', models.CharField(max_length=100)),
                ('review_current_ayat', models.IntegerField()),
                ('talqeen_task', models.IntegerField(choices=[(1, 'فئة 1'), (2, 'فئة 2'), (3, 'فئة 3'), (4, 'فئة 4'), (5, 'فئة 5'), (6, 'فئة 6'), (7, 'فئة 7')])),
                ('talqeen_previous_surah', models.CharField(max_length=100)),
                ('talqeen_previous_ayat', models.IntegerField()),
                ('talqeen_current_surah', models.CharField(max_length=100)),
                ('talqeen_current_ayat', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maqraapp.students')),
            ],
        ),
    ]
