# Generated by Django 5.1.4 on 2025-02-10 20:59

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0024_weeklylecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylecture',
            name='youtube_link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
