# Generated by Django 5.1.4 on 2025-02-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0026_admin_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
    ]
