# Generated by Django 5.1.4 on 2025-02-18 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0027_rename_message_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='halaqa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='maqraapp.halaqa'),
        ),
    ]
