# Generated by Django 5.1.4 on 2025-02-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0028_message_halaqa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='role',
        ),
        migrations.AddField(
            model_name='admin',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=256, verbose_name='الأسم الأول للأدمن'),
        ),
        migrations.AddField(
            model_name='admin',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=256, verbose_name='لقب الأدمن'),
        ),
        migrations.AddField(
            model_name='admin',
            name='second_name',
            field=models.CharField(default='Unknown', max_length=256, verbose_name='الأسم الثاني للأدمن'),
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default='default_username', max_length=250, verbose_name='اسم المستخدم'),
        ),
    ]
