# Generated by Django 5.1.4 on 2025-02-20 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('maqraapp', '0029_remove_admin_phone_number_remove_admin_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='username',
            field=models.CharField(default='default-username', max_length=256, unique=True, verbose_name='اسم المستخدم'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
