# Generated by Django 5.1.4 on 2025-02-20 18:00

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0036_alter_students_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='mobile_whatsapp',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='رقم الواتس'),
        ),
    ]
