# Generated by Django 5.1.4 on 2025-02-20 18:00

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0037_alter_teachers_mobile_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='رقم الجوال'),
        ),
    ]
