# Generated by Django 5.1.4 on 2025-02-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0038_alter_teachers_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='students',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='الإيميل'),
        ),
    ]
