# Generated by Django 5.1.4 on 2025-06-11 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0039_remove_students_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeread',
            name='msar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maqraapp.msar', verbose_name='المسار'),
        ),
    ]
