# Generated by Django 5.1.4 on 2025-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0040_typeread_msar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='الإيميل'),
        ),
    ]
