# Generated by Django 5.1.4 on 2025-06-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0042_alter_teachers_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اللغة')),
            ],
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='language',
        ),
        migrations.AddField(
            model_name='teachers',
            name='language',
            field=models.ManyToManyField(blank=True, to='maqraapp.language', verbose_name='اللغات التي تعرفها'),
        ),
    ]
