# Generated by Django 5.1.4 on 2025-06-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0043_language_remove_teachers_language_teachers_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, to='maqraapp.language', verbose_name='اللغات التي تعرفها'),
        ),
    ]
