# Generated by Django 5.1.4 on 2025-06-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0045_alter_teachers_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='الإيميل'),
        ),
    ]
