# Generated by Django 5.1.4 on 2025-06-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0046_alter_teachers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='username',
            field=models.CharField(max_length=256, unique=True, verbose_name='اسم المستخدم'),
        ),
    ]
