# Generated by Django 5.1.4 on 2025-06-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0047_alter_students_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='country',
        ),
    ]
