# Generated by Django 5.1.4 on 2025-06-17 20:40

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0048_remove_students_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='الأسم الأول للطالب'),
        ),
        migrations.AlterField(
            model_name='students',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maqraapp.language', verbose_name='اللغة التي تعرفها'),
        ),
        migrations.AlterField(
            model_name='students',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='لقب الطالب'),
        ),
        migrations.AlterField(
            model_name='students',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=50, verbose_name='كلمة المرور'),
        ),
        migrations.AlterField(
            model_name='students',
            name='second_name',
            field=models.CharField(max_length=50, verbose_name='الأسم الثاني للطالب'),
        ),
        migrations.AlterField(
            model_name='students',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='اسم المستخدم'),
        ),
        migrations.AlterField(
            model_name='students',
            name='whatsapp',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='رقم الواتس اب'),
        ),
    ]
