# Generated by Django 5.1.4 on 2025-06-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0049_alter_students_first_name_alter_students_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='username',
            field=models.CharField(default='default-username', max_length=255, unique=True, verbose_name='اسم المستخدم'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='اسم المستخدم'),
        ),
    ]
