# Generated by Django 5.1.4 on 2025-06-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0050_alter_supervisor_username_alter_teachers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=128, verbose_name='كلمة المرور'),
        ),
    ]
