# Generated by Django 5.1.4 on 2025-06-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0051_alter_students_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytalqeentask',
            old_name='memorized_ayat_count',
            new_name='Talqeen_ayat_count',
        ),
    ]
