# Generated by Django 5.1.4 on 2025-06-26 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0052_rename_memorized_ayat_count_dailytalqeentask_talqeen_ayat_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الرابط')),
                ('url', models.URLField(verbose_name='الرابط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='maqraapp.students', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'رابط الطالب',
                'verbose_name_plural': 'روابط الطلاب',
                'ordering': ['-created_at'],
            },
        ),
    ]
