# Generated by Django 5.1.4 on 2025-06-26 22:18

import django.db.models.deletion
import django.utils.timezone
import embed_video.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqraapp', '0053_studentlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'رسالة', 'verbose_name_plural': 'الرسائل'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='halaqa',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='message',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='تفعيل'),
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='وقت الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستلم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الموضوع'),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='وقت التعديل'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='وقت التعديل')),
                ('activate', models.BooleanField(default=True, verbose_name='تفعيل')),
                ('question', models.TextField(verbose_name='السؤال')),
                ('answer_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('image', 'Image')], max_length=10, verbose_name='نوع الإجابة')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='الإجابة النصية')),
                ('video_answer', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='الإجابة الفيديو')),
                ('image_answer', models.ImageField(blank=True, null=True, upload_to='faq_images/', verbose_name='الإجابة الصورة')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_answers', to=settings.AUTH_USER_MODEL, verbose_name='أجاب عليه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_questions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة',
                'ordering': ['-created_at'],
            },
        ),
    ]
